maximized = true
tabs = false
# no-multigrid = true
# wsl = true
# neovim-bin = "/home/brglng/.pixi/bin/nvim"

[font]
normal = ["Maple Mono NF CN", "Flog Symbols"]
hinting = "none"
size = 14.0

[box-drawing]
mode = "native"
