maximized = true
tabs = false
# no-multigrid = true
# wsl = true
# neovim-bin = "/home/brglng/.pixi/bin/nvim"

[font]
normal = ["LXGW Bright Code TC", "Symbols Nerd Font Mono", "Flog Symbols"]
    
hinting = "none"
size = 16.0

[box-drawing]
mode = "native"
