maximized = true
tabs = false
# no-multigrid = true
# wsl = true
# neovim-bin = "/home/brglng/.pixi/bin/nvim"

[font]
# normal = ["Maple Mono NF CN", "Flog Symbols"]
normal = ["LXGW Bright Code TC", "Flog Symbols"]
hinting = "none"
size = 16.0

[box-drawing]
mode = "native"
